/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$'
import { Route as AuthenticatedConnectAppsRouteImport } from './routes/_authenticated/connect-apps'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthCreatorRouteImport } from './routes/auth_.creator'
import { Route as CoordinateTokenRouteImport } from './routes/coordinate.$token'
import { Route as OauthAuthorizeRouteImport } from './routes/oauth/authorize'
import { Route as AuthenticatedPlansIndexRouteImport } from './routes/_authenticated/plans/index'
import { Route as AuthenticatedPlansPlanIdRouteImport } from './routes/_authenticated/plans/$planId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectAppsRoute =
  AuthenticatedConnectAppsRouteImport.update({
    id: '/connect-apps',
    path: '/connect-apps',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthCreatorRoute = AuthCreatorRouteImport.update({
  id: '/auth_/creator',
  path: '/auth/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinateTokenRoute = CoordinateTokenRouteImport.update({
  id: '/coordinate/$token',
  path: '/coordinate/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthAuthorizeRoute = OauthAuthorizeRouteImport.update({
  id: '/oauth/authorize',
  path: '/oauth/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlansIndexRoute = AuthenticatedPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlansPlanIdRoute =
  AuthenticatedPlansPlanIdRouteImport.update({
    id: '/plans/$planId',
    path: '/plans/$planId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/$': typeof AuthenticatedSplatRoute
  '/connect-apps': typeof AuthenticatedConnectAppsRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/auth/creator': typeof AuthCreatorRoute
  '/coordinate/$token': typeof CoordinateTokenRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/plans/$planId': typeof AuthenticatedPlansPlanIdRoute
  '/plans/': typeof AuthenticatedPlansIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/$': typeof AuthenticatedSplatRoute
  '/connect-apps': typeof AuthenticatedConnectAppsRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/auth/creator': typeof AuthCreatorRoute
  '/coordinate/$token': typeof CoordinateTokenRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/': typeof AuthenticatedIndexRoute
  '/plans/$planId': typeof AuthenticatedPlansPlanIdRoute
  '/plans': typeof AuthenticatedPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/$': typeof AuthenticatedSplatRoute
  '/_authenticated/connect-apps': typeof AuthenticatedConnectAppsRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/auth_/creator': typeof AuthCreatorRoute
  '/coordinate/$token': typeof CoordinateTokenRoute
  '/oauth/authorize': typeof OauthAuthorizeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/plans/$planId': typeof AuthenticatedPlansPlanIdRoute
  '/_authenticated/plans/': typeof AuthenticatedPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/$'
    | '/connect-apps'
    | '/discover'
    | '/family'
    | '/setup'
    | '/auth/creator'
    | '/coordinate/$token'
    | '/oauth/authorize'
    | '/plans/$planId'
    | '/plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/$'
    | '/connect-apps'
    | '/discover'
    | '/family'
    | '/setup'
    | '/auth/creator'
    | '/coordinate/$token'
    | '/oauth/authorize'
    | '/'
    | '/plans/$planId'
    | '/plans'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/$'
    | '/_authenticated/connect-apps'
    | '/_authenticated/discover'
    | '/_authenticated/family'
    | '/_authenticated/setup'
    | '/auth_/creator'
    | '/coordinate/$token'
    | '/oauth/authorize'
    | '/_authenticated/'
    | '/_authenticated/plans/$planId'
    | '/_authenticated/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCreatorRoute: typeof AuthCreatorRoute
  CoordinateTokenRoute: typeof CoordinateTokenRoute
  OauthAuthorizeRoute: typeof OauthAuthorizeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connect-apps': {
      id: '/_authenticated/connect-apps'
      path: '/connect-apps'
      fullPath: '/connect-apps'
      preLoaderRoute: typeof AuthenticatedConnectAppsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth_/creator': {
      id: '/auth_/creator'
      path: '/auth/creator'
      fullPath: '/auth/creator'
      preLoaderRoute: typeof AuthCreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinate/$token': {
      id: '/coordinate/$token'
      path: '/coordinate/$token'
      fullPath: '/coordinate/$token'
      preLoaderRoute: typeof CoordinateTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/authorize': {
      id: '/oauth/authorize'
      path: '/oauth/authorize'
      fullPath: '/oauth/authorize'
      preLoaderRoute: typeof OauthAuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plans/': {
      id: '/_authenticated/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AuthenticatedPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plans/$planId': {
      id: '/_authenticated/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof AuthenticatedPlansPlanIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
  AuthenticatedConnectAppsRoute: typeof AuthenticatedConnectAppsRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPlansPlanIdRoute: typeof AuthenticatedPlansPlanIdRoute
  AuthenticatedPlansIndexRoute: typeof AuthenticatedPlansIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedConnectAppsRoute: AuthenticatedConnectAppsRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPlansPlanIdRoute: AuthenticatedPlansPlanIdRoute,
  AuthenticatedPlansIndexRoute: AuthenticatedPlansIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCreatorRoute: AuthCreatorRoute,
  CoordinateTokenRoute: CoordinateTokenRoute,
  OauthAuthorizeRoute: OauthAuthorizeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
