/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedFamilyPortalRouteImport } from './routes/_authenticated/family-portal'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedPlansPlanIdRouteImport } from './routes/_authenticated/plans/$planId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFamilyPortalRoute =
  AuthenticatedFamilyPortalRouteImport.update({
    id: '/family-portal',
    path: '/family-portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlansPlanIdRoute =
  AuthenticatedPlansPlanIdRouteImport.update({
    id: '/plans/$planId',
    path: '/plans/$planId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/$': typeof AuthenticatedSplatRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/family-portal': typeof AuthenticatedFamilyPortalRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/plans/$planId': typeof AuthenticatedPlansPlanIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/$': typeof AuthenticatedSplatRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/family-portal': typeof AuthenticatedFamilyPortalRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/': typeof AuthenticatedIndexRoute
  '/plans/$planId': typeof AuthenticatedPlansPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/$': typeof AuthenticatedSplatRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/family-portal': typeof AuthenticatedFamilyPortalRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/plans/$planId': typeof AuthenticatedPlansPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/$'
    | '/discover'
    | '/family'
    | '/family-portal'
    | '/setup'
    | '/plans/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/$'
    | '/discover'
    | '/family'
    | '/family-portal'
    | '/setup'
    | '/'
    | '/plans/$planId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/$'
    | '/_authenticated/discover'
    | '/_authenticated/family'
    | '/_authenticated/family-portal'
    | '/_authenticated/setup'
    | '/_authenticated/'
    | '/_authenticated/plans/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/family-portal': {
      id: '/_authenticated/family-portal'
      path: '/family-portal'
      fullPath: '/family-portal'
      preLoaderRoute: typeof AuthenticatedFamilyPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plans/$planId': {
      id: '/_authenticated/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof AuthenticatedPlansPlanIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedFamilyPortalRoute: typeof AuthenticatedFamilyPortalRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPlansPlanIdRoute: typeof AuthenticatedPlansPlanIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedFamilyPortalRoute: AuthenticatedFamilyPortalRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPlansPlanIdRoute: AuthenticatedPlansPlanIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
