create table if not exists public.plan_notifications (
    id bigint generated by default as identity primary key,
    plan_id bigint not null references public.plans(id) on delete cascade,
    trusted_contact_id bigint not null references public.trusted_contacts(id) on delete cascade,
    recipient_name text not null,
    recipient_email text,
    status text not null default 'pending'
        check (status in ('pending', 'sent', 'failed')),
    provider_id text,
    error_message text,
    attempted_at timestamptz,
    sent_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (plan_id, trusted_contact_id)
);

create index if not exists plan_notifications_plan_idx
    on public.plan_notifications (plan_id);

alter table public.plan_notifications enable row level security;

drop policy if exists "Household members can view plan notifications" on public.plan_notifications;
create policy "Household members can view plan notifications"
on public.plan_notifications for select
to authenticated
using (
    exists (
        select 1
        from public.plans plan
        join public.household_members member on member.household_id = plan.household_id
        where plan.id = plan_notifications.plan_id
          and member.user_id = auth.uid()
    )
);
