-- One-pass upgrade from the household schema to the family schema.
--
-- Several earlier migration files were rewritten in place rather than added to,
-- so re-running them does not transform a database that already exists. This
-- file does the transformation, and folds in the three later feature migrations
-- so an existing database can be brought fully up to date in a single run.
--
-- Safe to run on a database that is already partly or fully migrated: every
-- step is guarded, and running it twice changes nothing the second time.

-- 0. Activity metadata removed by editing the original migration -------------------

alter table public.activities
    drop column if exists price_remarks,
    drop column if exists slots_availability,
    drop column if exists mobility_notes,
    drop column if exists intensity,
    drop column if exists content_hash;

-- 1. households -> families, household_members -> family_accounts -----------------

do $$
begin
    if to_regclass('public.households') is not null
       and to_regclass('public.families') is null then
        alter table public.households rename to families;
    end if;

    if to_regclass('public.household_members') is not null
       and to_regclass('public.family_accounts') is null then
        alter table public.household_members rename to family_accounts;
    end if;

    if exists (select 1 from information_schema.columns
               where table_schema = 'public' and table_name = 'family_accounts'
                 and column_name = 'household_id') then
        alter table public.family_accounts rename column household_id to family_id;
    end if;

    if exists (select 1 from information_schema.columns
               where table_schema = 'public' and table_name = 'older_adult_profiles'
                 and column_name = 'household_id') then
        alter table public.older_adult_profiles rename column household_id to family_id;
    end if;

    if exists (select 1 from information_schema.columns
               where table_schema = 'public' and table_name = 'plans'
                 and column_name = 'household_id') then
        alter table public.plans rename column household_id to family_id;
    end if;
end $$;

-- The per-account relationship now lives on family_member_older_adults.
alter table public.family_accounts drop column if exists relationship;

alter table public.families
    add column if not exists owner_email text,
    add column if not exists owner_email_verified_at timestamptz;

alter table public.older_adult_profiles
    add column if not exists email text;

-- 2. Family members, and the relationship held per older adult --------------------

create table if not exists public.family_members (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    name text not null,
    email text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.family_member_older_adults (
    family_member_id bigint not null references public.family_members(id) on delete cascade,
    older_adult_id bigint not null references public.older_adult_profiles(id) on delete cascade,
    relationship text not null,
    created_at timestamptz not null default now(),
    primary key (family_member_id, older_adult_id)
);

create unique index if not exists family_members_family_email_idx
    on public.family_members (family_id, lower(email));
create index if not exists family_member_older_adults_older_adult_idx
    on public.family_member_older_adults (older_adult_id);

-- 3. Carry existing trusted contacts across, then retire the old table ------------
-- Contacts with no email address are not carried over: the family flow reaches
-- people only by email, so such a record could never take part in a decision.

do $$
begin
    if to_regclass('public.trusted_contacts') is null then
        return;
    end if;

    -- One family member per (family, email); the earliest contact wins the name.
    insert into public.family_members (family_id, name, email, created_at)
    select distinct on (profile.family_id, lower(contact.email))
           profile.family_id, contact.name, lower(contact.email), contact.created_at
    from public.trusted_contacts contact
    join public.older_adult_profiles profile on profile.id = contact.older_adult_id
    where contact.email is not null and contact.email <> ''
    order by profile.family_id, lower(contact.email), contact.created_at
    on conflict do nothing;

    insert into public.family_member_older_adults (family_member_id, older_adult_id, relationship)
    select member.id, contact.older_adult_id, contact.relationship
    from public.trusted_contacts contact
    join public.older_adult_profiles profile on profile.id = contact.older_adult_id
    join public.family_members member
      on member.family_id = profile.family_id
     and member.email = lower(contact.email)
    where contact.email is not null and contact.email <> ''
    on conflict do nothing;

    -- Repoint delivery history before the old table disappears.
    if exists (select 1 from information_schema.columns
               where table_schema = 'public' and table_name = 'plan_notifications'
                 and column_name = 'trusted_contact_id') then
        alter table public.plan_notifications add column if not exists family_member_id bigint;

        update public.plan_notifications notification
        set family_member_id = matched.member_id
        from (
            select contact.id as contact_id, member.id as member_id
            from public.trusted_contacts contact
            join public.older_adult_profiles profile on profile.id = contact.older_adult_id
            join public.family_members member
              on member.family_id = profile.family_id
             and member.email = lower(contact.email)
        ) as matched
        where notification.trusted_contact_id = matched.contact_id;

        delete from public.plan_notifications where family_member_id is null;

        alter table public.plan_notifications
            drop constraint if exists plan_notifications_plan_id_trusted_contact_id_key;
        alter table public.plan_notifications drop column trusted_contact_id;
        alter table public.plan_notifications alter column family_member_id set not null;
        alter table public.plan_notifications
            add constraint plan_notifications_family_member_fk
            foreign key (family_member_id) references public.family_members(id) on delete cascade;
        alter table public.plan_notifications
            add constraint plan_notifications_plan_member_key
            unique (plan_id, family_member_id);
    end if;

    drop table public.trusted_contacts cascade;
end $$;

-- 4. Plan decision state ----------------------------------------------------------

alter table public.plans drop constraint if exists plans_status_check;
alter table public.plans add constraint plans_status_check
    check (status in ('draft', 'awaiting_approval', 'approved', 'rejected', 'shared', 'cancelled'));

alter table public.plans
    add column if not exists decision_by_family_member_id bigint references public.family_members(id),
    add column if not exists decided_at timestamptz,
    add column if not exists decision_reason text;

drop index if exists public.plans_household_idx;
create index if not exists plans_family_idx on public.plans (family_id);

-- 5. Verification, invitations, approval links, decision delivery ------------------

create table if not exists public.family_email_verifications (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    email text not null,
    code_hash text not null,
    expires_at timestamptz not null,
    verified_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.family_member_invitations (
    id bigint generated by default as identity primary key,
    family_member_id bigint not null references public.family_members(id) on delete cascade,
    token_hash text not null unique,
    expires_at timestamptz not null,
    accepted_at timestamptz,
    created_at timestamptz not null default now()
);

create table if not exists public.plan_approval_requests (
    id bigint generated by default as identity primary key,
    plan_id bigint not null references public.plans(id) on delete cascade,
    family_member_id bigint not null references public.family_members(id) on delete cascade,
    token_hash text not null unique,
    status text not null default 'pending' check (status in ('pending', 'used', 'expired')),
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null default now(),
    unique (plan_id, family_member_id)
);

create table if not exists public.plan_decision_notifications (
    id bigint generated by default as identity primary key,
    plan_id bigint not null references public.plans(id) on delete cascade,
    recipient_role text not null check (recipient_role in ('family_member', 'older_adult')),
    family_member_id bigint references public.family_members(id) on delete cascade,
    older_adult_id bigint references public.older_adult_profiles(id) on delete cascade,
    recipient_name text not null,
    recipient_email text,
    status text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
    provider_id text,
    error_message text,
    attempted_at timestamptz,
    sent_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    -- Exactly one recipient reference, matching the declared role.
    constraint plan_decision_notifications_recipient_check check (
        (recipient_role = 'family_member' and family_member_id is not null and older_adult_id is null)
        or (recipient_role = 'older_adult' and older_adult_id is not null and family_member_id is null)
    )
);

create index if not exists family_email_verifications_family_idx
    on public.family_email_verifications (family_id, created_at desc);
create index if not exists family_member_invitations_member_idx
    on public.family_member_invitations (family_member_id, created_at desc);
create index if not exists plan_approval_requests_plan_idx
    on public.plan_approval_requests (plan_id);
create unique index if not exists plan_decision_notifications_family_member_idx
    on public.plan_decision_notifications (plan_id, family_member_id)
    where family_member_id is not null;
create unique index if not exists plan_decision_notifications_older_adult_idx
    on public.plan_decision_notifications (plan_id, older_adult_id)
    where older_adult_id is not null;
create index if not exists plan_decision_notifications_plan_idx
    on public.plan_decision_notifications (plan_id);

-- 6. Row level security ------------------------------------------------------------

alter table public.families enable row level security;
alter table public.family_accounts enable row level security;
alter table public.family_members enable row level security;
alter table public.family_member_older_adults enable row level security;
alter table public.family_email_verifications enable row level security;
alter table public.family_member_invitations enable row level security;
alter table public.plan_approval_requests enable row level security;
alter table public.plan_decision_notifications enable row level security;

drop policy if exists "Household members can view plans" on public.plans;
drop policy if exists "Household members can view support offers" on public.plan_support_offers;
drop policy if exists "Household members can view plan notifications" on public.plan_notifications;
drop policy if exists "Family accounts can view plans" on public.plans;
drop policy if exists "Family accounts can view family members" on public.family_members;
drop policy if exists "Family accounts can view support offers" on public.plan_support_offers;
drop policy if exists "Family accounts can view plan notifications" on public.plan_notifications;
drop policy if exists "Family accounts can view plan decision notifications" on public.plan_decision_notifications;
drop policy if exists "Members can view activity recommendations" on public.activity_recommendations;

create policy "Family accounts can view plans"
on public.plans for select to authenticated
using (exists (
    select 1 from public.family_accounts account
    where account.family_id = plans.family_id and account.user_id = auth.uid()
));

create policy "Family accounts can view family members"
on public.family_members for select to authenticated
using (exists (
    select 1 from public.family_accounts account
    where account.family_id = family_members.family_id and account.user_id = auth.uid()
));

create policy "Family accounts can view support offers"
on public.plan_support_offers for select to authenticated
using (exists (
    select 1 from public.plans plan
    join public.family_accounts account on account.family_id = plan.family_id
    where plan.id = plan_support_offers.plan_id and account.user_id = auth.uid()
));

create policy "Family accounts can view plan notifications"
on public.plan_notifications for select to authenticated
using (exists (
    select 1 from public.plans plan
    join public.family_accounts account on account.family_id = plan.family_id
    where plan.id = plan_notifications.plan_id and account.user_id = auth.uid()
));

create policy "Family accounts can view plan decision notifications"
on public.plan_decision_notifications for select to authenticated
using (exists (
    select 1 from public.plans plan
    join public.family_accounts account on account.family_id = plan.family_id
    where plan.id = plan_decision_notifications.plan_id and account.user_id = auth.uid()
));

create policy "Members can view activity recommendations"
on public.activity_recommendations for select to authenticated
using (exists (
    select 1 from public.older_adult_profiles profile
    join public.family_accounts account on account.family_id = profile.family_id
    where profile.id = activity_recommendations.older_adult_id
      and account.user_id = auth.uid()
));
