create table if not exists public.activities (
    id bigint generated by default as identity primary key,
    dedupe_key text not null unique,
    name text not null,
    description text,
    location text not null,
    start_at timestamptz not null,
    end_at timestamptz,
    cost numeric(10, 2),
    currency text not null default 'SGD',
    info_link text not null,
    signup_link text,
    tags text[],
    suitability_score numeric(5, 2),
    engagement_score numeric(5, 2),
    total_score numeric(5, 2),
    status text not null default 'active'
        check (status in ('active', 'expired', 'cancelled')),
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    last_checked_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    created_at timestamptz not null default now()
);

-- One family coordinating support for one or more older adults.
create table if not exists public.families (
    id bigint generated by default as identity primary key,
    name text not null,
    created_by uuid not null references auth.users(id),
    created_at timestamptz not null default now()
);

-- Signed-in accounts that may act on behalf of the family.
create table if not exists public.family_accounts (
    family_id bigint not null references public.families(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    role text not null check (role in ('owner', 'family_member', 'caregiver')),
    created_at timestamptz not null default now(),
    primary key (family_id, user_id)
);

create table if not exists public.older_adult_profiles (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    name text not null,
    preferred_name text,
    age integer check (age between 0 and 130),
    language text,
    email text,
    mobility_notes text,
    transport_notes text,
    created_by uuid not null references auth.users(id),
    created_at timestamptz not null default now()
);

-- People the family can ask for support. A family member does not need an
-- account: they are reached by email and act through signed links.
create table if not exists public.family_members (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    name text not null,
    email text not null,
    created_at timestamptz not null default now()
);

-- One family member can hold a different relationship to each older adult,
-- for example daughter to one parent and sister to another.
create table if not exists public.family_member_older_adults (
    family_member_id bigint not null references public.family_members(id) on delete cascade,
    older_adult_id bigint not null references public.older_adult_profiles(id) on delete cascade,
    relationship text not null,
    created_at timestamptz not null default now(),
    primary key (family_member_id, older_adult_id)
);

-- One invitation per email address within a family.
create unique index if not exists family_members_family_email_idx
    on public.family_members (family_id, lower(email));

create index if not exists family_member_older_adults_older_adult_idx
    on public.family_member_older_adults (older_adult_id);

create index if not exists activities_start_at_idx on public.activities (start_at);
create index if not exists activities_location_idx on public.activities (location);
create index if not exists activities_active_start_idx on public.activities (status, start_at);
create index if not exists activities_score_idx on public.activities (total_score desc nulls last);

alter table public.activities enable row level security;
alter table public.profiles enable row level security;
alter table public.families enable row level security;
alter table public.family_accounts enable row level security;
alter table public.older_adult_profiles enable row level security;
alter table public.family_members enable row level security;
alter table public.family_member_older_adults enable row level security;

drop policy if exists "Anyone can view active activities" on public.activities;
create policy "Anyone can view active activities"
on public.activities for select
to anon, authenticated
using (status = 'active' and start_at >= now());

drop policy if exists "Family accounts can view family members" on public.family_members;
create policy "Family accounts can view family members"
on public.family_members for select
to authenticated
using (
    exists (
        select 1
        from public.family_accounts account
        where account.family_id = family_members.family_id
          and account.user_id = auth.uid()
    )
);
