create table if not exists public.plan_notifications (
    id bigint generated by default as identity primary key,
    plan_id bigint not null references public.plans(id) on delete cascade,
    family_member_id bigint not null references public.family_members(id) on delete cascade,
    recipient_name text not null,
    recipient_email text,
    status text not null default 'pending'
        check (status in ('pending', 'sent', 'failed')),
    provider_id text,
    error_message text,
    attempted_at timestamptz,
    sent_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (plan_id, family_member_id)
);

create index if not exists plan_notifications_plan_idx
    on public.plan_notifications (plan_id);

alter table public.plan_notifications enable row level security;

drop policy if exists "Family accounts can view plan notifications" on public.plan_notifications;
create policy "Family accounts can view plan notifications"
on public.plan_notifications for select
to authenticated
using (
    exists (
        select 1
        from public.plans plan
        join public.family_accounts account on account.family_id = plan.family_id
        where plan.id = plan_notifications.plan_id
          and account.user_id = auth.uid()
    )
);
