-- Coordination replaces a single approval decision with three shared tasks the
-- whole family can see and act on: approval, registration, and transport.
--
-- A plan becomes `ready` when it is approved and both practical tasks are
-- resolved, and `completed` once the activity has happened.

alter table public.plans drop constraint if exists plans_status_check;
alter table public.plans add constraint plans_status_check
    check (status in (
        'draft', 'coordinating', 'ready', 'completed',
        'rejected', 'cancelled',
        -- Retained so existing rows stay valid until they are migrated below.
        'awaiting_approval', 'approved', 'shared'
    ));

update public.plans set status = 'coordinating' where status = 'awaiting_approval';
update public.plans set status = 'ready' where status in ('approved', 'shared');

alter table public.plans drop constraint if exists plans_status_check;
alter table public.plans add constraint plans_status_check
    check (status in ('draft', 'coordinating', 'ready', 'completed', 'rejected', 'cancelled'));

alter table public.plans
    add column if not exists ready_at timestamptz,
    add column if not exists completed_at timestamptz;

-- One coordination record per plan. `version` guards the whole record so two
-- people acting at the same moment cannot both win.
create table if not exists public.plan_coordination (
    id bigint generated by default as identity primary key,
    plan_id bigint not null unique references public.plans(id) on delete cascade,
    version integer not null default 1,
    launched_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.plan_coordination_tasks (
    id bigint generated by default as identity primary key,
    coordination_id bigint not null references public.plan_coordination(id) on delete cascade,
    task_type text not null check (task_type in ('approval', 'registration', 'transport')),
    status text not null default 'open'
        check (status in ('open', 'claimed', 'done', 'not_needed', 'approved', 'rejected')),
    owner_family_member_id bigint references public.family_members(id) on delete set null,
    decided_by_family_member_id bigint references public.family_members(id) on delete set null,
    reason text,
    version integer not null default 1,
    resolved_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (coordination_id, task_type)
);

-- Everything the family did, in plain language, for the shared history panel.
create table if not exists public.plan_coordination_events (
    id bigint generated by default as identity primary key,
    coordination_id bigint not null references public.plan_coordination(id) on delete cascade,
    task_type text check (task_type in ('approval', 'registration', 'transport')),
    action text not null,
    actor_family_member_id bigint references public.family_members(id) on delete set null,
    actor_name text not null,
    detail text,
    created_at timestamptz not null default now()
);

-- One reusable link per family member per plan. It is not single use: family
-- members return to the same link to watch progress after they have acted.
create table if not exists public.plan_coordination_links (
    id bigint generated by default as identity primary key,
    plan_id bigint not null references public.plans(id) on delete cascade,
    family_member_id bigint not null references public.family_members(id) on delete cascade,
    token_hash text not null unique,
    expires_at timestamptz not null,
    revoked_at timestamptz,
    created_at timestamptz not null default now(),
    unique (plan_id, family_member_id)
);

create index if not exists plan_coordination_tasks_coordination_idx
    on public.plan_coordination_tasks (coordination_id);
create index if not exists plan_coordination_events_coordination_idx
    on public.plan_coordination_events (coordination_id, created_at desc);
create index if not exists plan_coordination_links_plan_idx
    on public.plan_coordination_links (plan_id);

alter table public.plan_coordination enable row level security;
alter table public.plan_coordination_tasks enable row level security;
alter table public.plan_coordination_events enable row level security;
alter table public.plan_coordination_links enable row level security;

-- Support offers are no longer written to. The table is kept for now so the
-- migration can be reversed; a later change removes it.
