alter table public.plans drop constraint if exists plans_status_check;
alter table public.plans add constraint plans_status_check
    check (status in ('draft', 'awaiting_approval', 'approved', 'rejected', 'shared', 'cancelled'));

alter table public.plans
    add column if not exists decision_by_family_member_id bigint references public.family_members(id),
    add column if not exists decided_at timestamptz,
    add column if not exists decision_reason text;

create table if not exists public.plan_approval_requests (
    id bigint generated by default as identity primary key,
    plan_id bigint not null references public.plans(id) on delete cascade,
    family_member_id bigint not null references public.family_members(id) on delete cascade,
    token_hash text not null unique,
    status text not null default 'pending' check (status in ('pending', 'used', 'expired')),
    expires_at timestamptz not null,
    used_at timestamptz,
    created_at timestamptz not null default now(),
    unique (plan_id, family_member_id)
);

create index if not exists plan_approval_requests_plan_idx
    on public.plan_approval_requests (plan_id);

alter table public.plan_approval_requests enable row level security;
