-- Delivery record for the "what the family decided" email, one row per
-- recipient. Family members and the older adult are both recipients, so the
-- result can be reported honestly and failures can be retried.
create table if not exists public.plan_decision_notifications (
    id bigint generated by default as identity primary key,
    plan_id bigint not null references public.plans(id) on delete cascade,
    recipient_role text not null check (recipient_role in ('family_member', 'older_adult')),
    family_member_id bigint references public.family_members(id) on delete cascade,
    older_adult_id bigint references public.older_adult_profiles(id) on delete cascade,
    recipient_name text not null,
    recipient_email text,
    status text not null default 'pending'
        check (status in ('pending', 'sent', 'failed')),
    provider_id text,
    error_message text,
    attempted_at timestamptz,
    sent_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    -- Exactly one recipient reference, matching the declared role.
    constraint plan_decision_notifications_recipient_check check (
        (recipient_role = 'family_member' and family_member_id is not null and older_adult_id is null)
        or (recipient_role = 'older_adult' and older_adult_id is not null and family_member_id is null)
    )
);

create unique index if not exists plan_decision_notifications_family_member_idx
    on public.plan_decision_notifications (plan_id, family_member_id)
    where family_member_id is not null;

create unique index if not exists plan_decision_notifications_older_adult_idx
    on public.plan_decision_notifications (plan_id, older_adult_id)
    where older_adult_id is not null;

create index if not exists plan_decision_notifications_plan_idx
    on public.plan_decision_notifications (plan_id);

alter table public.plan_decision_notifications enable row level security;

drop policy if exists "Family accounts can view plan decision notifications"
    on public.plan_decision_notifications;
create policy "Family accounts can view plan decision notifications"
on public.plan_decision_notifications for select
to authenticated
using (
    exists (
        select 1
        from public.plans plan
        join public.family_accounts account on account.family_id = plan.family_id
        where plan.id = plan_decision_notifications.plan_id
          and account.user_id = auth.uid()
    )
);
