create table if not exists public.activity_recommendations (
    id bigint generated by default as identity primary key,
    older_adult_id bigint not null references public.older_adult_profiles(id) on delete cascade,
    activity_id bigint not null references public.activities(id) on delete cascade,
    recommendation_score numeric(5, 2) not null check (recommendation_score between 0 and 100),
    match_factors jsonb not null default '{}'::jsonb,
    request_context jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    expires_at timestamptz,
    unique (older_adult_id, activity_id)
);

create index if not exists activity_recommendations_older_adult_idx
    on public.activity_recommendations (older_adult_id, recommendation_score desc);

alter table public.activity_recommendations enable row level security;

drop policy if exists "Members can view activity recommendations" on public.activity_recommendations;
create policy "Members can view activity recommendations"
on public.activity_recommendations for select
to authenticated
using (
    exists (
        select 1
        from public.older_adult_profiles profile
        join public.household_members member on member.household_id = profile.household_id
        where profile.id = activity_recommendations.older_adult_id
          and member.user_id = auth.uid()
    )
);
