create table if not exists public.activity_ingestion_runs (
    id bigint generated by default as identity primary key,
    provider text not null,
    status text not null check (status in ('running', 'succeeded', 'failed')),
    started_at timestamptz not null default now(),
    finished_at timestamptz,
    candidates_found integer not null default 0,
    activities_saved integer not null default 0,
    activities_expired integer not null default 0,
    error_message text
);

create table if not exists public.activities (
    id bigint generated by default as identity primary key,
    dedupe_key text not null unique,
    name text not null,
    description text,
    location text not null,
    start_at timestamptz not null,
    end_at timestamptz,
    cost numeric(10, 2),
    currency text not null default 'SGD',
    price_remarks text,
    slots_availability text,
    info_link text not null,
    signup_link text,
    mobility_notes text,
    intensity text,
    tags text[],
    suitability_score numeric(5, 2),
    engagement_score numeric(5, 2),
    total_score numeric(5, 2),
    status text not null default 'active'
        check (status in ('active', 'expired', 'cancelled')),
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now(),
    last_checked_at timestamptz not null default now(),
    content_hash text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.households (
    id bigint generated by default as identity primary key,
    name text not null,
    created_by uuid not null references auth.users(id),
    created_at timestamptz not null default now()
);

create table if not exists public.household_members (
    household_id bigint not null references public.households(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    role text not null check (role in ('owner', 'family_member', 'caregiver')),
    relationship text,
    created_at timestamptz not null default now(),
    primary key (household_id, user_id)
);

create table if not exists public.older_adult_profiles (
    id bigint generated by default as identity primary key,
    household_id bigint not null references public.households(id) on delete cascade,
    name text not null,
    preferred_name text,
    age integer check (age between 0 and 130),
    language text,
    mobility_notes text,
    transport_notes text,
    created_by uuid not null references auth.users(id),
    created_at timestamptz not null default now()
);

create table if not exists public.trusted_contacts (
    id bigint generated by default as identity primary key,
    older_adult_id bigint not null references public.older_adult_profiles(id) on delete cascade,
    name text not null,
    relationship text not null,
    email text,
    phone text,
    consent_status text not null default 'pending'
        check (consent_status in ('pending', 'confirmed', 'revoked')),
    created_at timestamptz not null default now()
);

create index if not exists activities_start_at_idx on public.activities (start_at);
create index if not exists activities_location_idx on public.activities (location);
create index if not exists activities_active_start_idx on public.activities (status, start_at);
create index if not exists activities_score_idx on public.activities (total_score desc nulls last);

alter table public.activity_ingestion_runs enable row level security;
alter table public.activities enable row level security;
alter table public.profiles enable row level security;
alter table public.households enable row level security;
alter table public.household_members enable row level security;
alter table public.older_adult_profiles enable row level security;
alter table public.trusted_contacts enable row level security;

drop policy if exists "Anyone can view active activities" on public.activities;
create policy "Anyone can view active activities"
on public.activities for select
to anon, authenticated
using (status = 'active' and start_at >= now());
