create table if not exists public.plans (
    id bigint generated by default as identity primary key,
    household_id bigint not null references public.households(id) on delete cascade,
    older_adult_id bigint not null references public.older_adult_profiles(id) on delete cascade,
    activity_id bigint not null references public.activities(id),
    status text not null default 'draft'
        check (status in ('draft', 'awaiting_approval', 'shared', 'cancelled')),
    created_by uuid not null references auth.users(id),
    approved_by uuid references auth.users(id),
    approved_at timestamptz,
    shared_at timestamptz,
    cancelled_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.plan_support_offers (
    id bigint generated by default as identity primary key,
    plan_id bigint not null references public.plans(id) on delete cascade,
    offered_by uuid not null references auth.users(id) on delete cascade,
    support_type text not null
        check (support_type in ('join', 'remind', 'transport', 'alternative', 'booking', 'encourage')),
    note text,
    status text not null default 'offered'
        check (status in ('offered', 'withdrawn')),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (plan_id, offered_by, support_type)
);

create index if not exists plans_household_idx on public.plans (household_id);
create index if not exists plans_older_adult_idx on public.plans (older_adult_id);
create index if not exists plans_status_idx on public.plans (status);
create index if not exists plan_support_offers_plan_idx on public.plan_support_offers (plan_id);

alter table public.plans enable row level security;
alter table public.plan_support_offers enable row level security;

drop policy if exists "Household members can view plans" on public.plans;
create policy "Household members can view plans"
on public.plans for select
to authenticated
using (
    exists (
        select 1
        from public.household_members member
        where member.household_id = plans.household_id
          and member.user_id = auth.uid()
    )
);

drop policy if exists "Household members can view support offers" on public.plan_support_offers;
create policy "Household members can view support offers"
on public.plan_support_offers for select
to authenticated
using (
    exists (
        select 1
        from public.plans plan
        join public.household_members member on member.household_id = plan.household_id
        where plan.id = plan_support_offers.plan_id
          and member.user_id = auth.uid()
    )
);
