alter table public.families
    add column if not exists owner_email text,
    add column if not exists owner_email_verified_at timestamptz;

create table if not exists public.family_email_verifications (
    id bigint generated by default as identity primary key,
    family_id bigint not null references public.families(id) on delete cascade,
    email text not null,
    code_hash text not null,
    expires_at timestamptz not null,
    verified_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists family_email_verifications_family_idx
    on public.family_email_verifications (family_id, created_at desc);

create table if not exists public.family_member_invitations (
    id bigint generated by default as identity primary key,
    family_member_id bigint not null references public.family_members(id) on delete cascade,
    token_hash text not null unique,
    expires_at timestamptz not null,
    accepted_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists family_member_invitations_member_idx
    on public.family_member_invitations (family_member_id, created_at desc);

alter table public.family_email_verifications enable row level security;
alter table public.family_member_invitations enable row level security;
